
import { delay, getStorage, INITIAL_USERS, DB_KEYS, INITIAL_PASSWORDS } from '../mockData';

// Point to local backend to access new endpoints like DROP DATABASE
export const API_URL = 'https://api-kohost.kolab.top/api'; 
export const TUNNEL_API_URL = 'https://cloudflare.kolab.top'; 
export const APACHE_API_URL = 'https://api-apache.kolab.top';

export let isBackendOffline = false;

export const setBackendOffline = (status: boolean) => {
    isBackendOffline = status;
};

export const getAuthHeaders = () => {
  const token = localStorage.getItem('kp_token');
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  return headers;
};

export const getAuthHeadersMultipart = () => {
  const token = localStorage.getItem('kp_token');
  const headers: Record<string, string> = {};
  if (token) headers['Authorization'] = `Bearer ${token}`;
  return headers;
};

export const handleResponse = async (res: Response) => {
  if (!res.ok) {
    let errorMessage = res.statusText || 'An error occurred';
    try {
        const error = await res.json();
        if (error && error.message) errorMessage = error.message;
    } catch (e) {
        // Response was not JSON, keep statusText
    }
    throw new Error(errorMessage);
  }
  return res.json();
};

export async function fetchWithMockFallback<T>(
    fetchFn: () => Promise<T>, 
    mockFn: () => Promise<T>
): Promise<T> {
    if (isBackendOffline) return mockFn();

    try {
        return await fetchFn();
    } catch (error: any) {
        // Fallback to mock data on:
        // 1. Network errors (offline, connection refused)
        // 2. Server errors (404 Not Found, 500 Internal Server Error, etc) that return generic messages
        const isNetworkError = error.message.includes('Failed to fetch') || 
                               error.message.includes('NetworkError') || 
                               error.name === 'TypeError';
                               
        // Check for common error messages generated by handleResponse or default browser behavior for broken APIs
        // Note: We don't fallback on 404 for specific routes if we expect them to exist in dev, 
        // but if the whole backend is down/unreachable, we fallback.
        const isServerError = error.message === 'An error occurred' || 
                              error.message === 'Internal Server Error' ||
                              error.message.includes('JSON'); 

        if (isNetworkError || isServerError) {
            if (!isBackendOffline) {
                console.warn(`Backend unreachable or erroring (${error.message}). Switching to client-side mock data.`);
                setBackendOffline(true);
            }
            return mockFn();
        }
        throw error;
    }
}
